language: ruby
cache: bundler
dist: xenial

rvm: 2.1.9

matrix:
  include:
    - name: "Validate Commit Message"
      language: python
      script:
      - pip install gitlint
      - wget https://raw.githubusercontent.com/SUSE-Cloud/automation/master/scripts/jenkins/gitlint.ini
      - gitlint --commits master..HEAD -C gitlint.ini
    - name: "Syntaxcheck"
      gemfile: Gemfile
      script:
      - bundle exec rake syntaxcheck
    - name: "Validate Framework (RSpec)"
      gemfile: Gemfile
      script:
      - bundle exec rake spec
    - name: "Validate Databags"
      gemfile: Gemfile
      script:
      - bundle exec crowbar-validate-databags chef/data_bags/crowbar

before_install:
  - rvm @global do gem install bundler -v '< 2.0.0'
